-- TABLAS PARA BASE DE DATOS VENTAS

CREATE TABLE "CLIENTES" 
(
	"ID_CLIENTE"	TEXT NOT NULL,
	"NOMBRE"	TEXT NOT NULL,
	"DIRECCION"	TEXT,
	"TELEFONO"	INTEGER,
	PRIMARY KEY("ID_CLIENTE")
);

CREATE TABLE "FACTURAS" 
(
	"ID_FACTURA"	TEXT NOT NULL,
	"FECHA"	INTEGER,
	"ID_CLIENTE"	INTEGER NOT NULL,
	FOREIGN KEY("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE")
);