-- ADMINISTRANDO ROLES Y USUARIOS

-- Roles de administradores 
CREATE ROLE ADMIN_CLINIC;

GRANT USAGE ON SCHEMA CLINIC TO ADMIN_CLINIC;


GRANT SELECT,INSERT,UPDATE,TRUNCATE,DELETE
ON 
CLINIC.PATIENT,
CLINIC.SPECIALIST,
CLINIC.DATE_MED,
CLINIC.DATE_MED_DETAILS,
CLINIC.MED_RECORDS,
CLINIC.MED_RECORDS_DETAILS
TO ADMIN_CLINIC WITH GRANT OPTION;

DROP USER IF EXISTS admin01; -- PRUEBA Y ERROR
DROP USER IF EXISTS admin02;
DROP USER IF EXISTS admin03;

CREATE USER admin01 WITH PASSWORD 'data#clinic_pg202401' CONNECTION LIMIT 1 IN ROLE ADMIN_CLINIC;
CREATE USER admin02 WITH PASSWORD 'data#clinic_pg202402' CONNECTION LIMIT 1 IN ROLE ADMIN_CLINIC;
CREATE USER admin03 WITH PASSWORD 'data#clinic_pg202403' CONNECTION LIMIT 1 IN ROLE ADMIN_CLINIC;


-- Roles de analistas
CREATE ROLE ANALYST_CLINIC;

GRANT USAGE ON SCHEMA CLINIC TO ANALYST_CLINIC;

GRANT SELECT
ON 
CLINIC.PATIENT,
CLINIC.SPECIALIST,
CLINIC.DATE_MED,
CLINIC.DATE_MED_DETAILS,
CLINIC.MED_RECORDS,
CLINIC.MED_RECORDS_DETAILS
TO ANALYST_CLINIC WITH GRANT OPTION;


CREATE USER analyst0001 WITH PASSWORD 'analyst#clinic_pg20240001' CONNECTION LIMIT 1 IN ROLE ANALYST_CLINIC;
CREATE USER analyst0002 WITH PASSWORD 'analyst#clinic_pg20240002' CONNECTION LIMIT 1 IN ROLE ANALYST_CLINIC;
CREATE USER analyst0003 WITH PASSWORD 'analyst#clinic_pg20240003' CONNECTION LIMIT 1 IN ROLE ANALYST_CLINIC;

-- SOLO HAY DOS ANALISTAS
DROP USER analyst0003;

-- VERIFIQUEMOS LOS USUARIOS CREADOS
SELECT * FROM pg_user;