
/* UPDATING AND DELETING RECORDS FROM DIFFERENT TABLES */
SELECT *
FROM CLINIC.PATIENT;

UPDATE CLINIC.PATIENT SET 
    CITY = 'GAM',
    STATE_NM = 'CDMX' 
WHERE CITY = 'MEXICO'

SELECT *
FROM CLINIC.PATIENT;

DELETE FROM CLINIC.PATIENT WHERE ID_PATIENT = 'P-0009';

SELECT *
FROM CLINIC.PATIENT
ORDER BY ID_PATIENT;

-- Lets see what happend if we look the same record

SELECT *
FROM CLINIC.MED_RECORDS_DETAILS 
WHERE ID_PATIENT = 'P-0009'

/* FILTER DATA */

--DISPLAY ALL PATIENTS WITH FULL NAME THAT LIVES IN MONTERREY
SELECT ID_PATIENT,CONCAT(ALL_NAMES,' ',LAST_NAME) AS FULL_NAME,PHONE_NBR AS NUMBER_PHONE
FROM CLINIC.PATIENT
WHERE CITY = 'MONTERREY'
LIMIT 15;

-- DISPLAY ALL NAMES MALE PATIENTS WITH CURRENT AGE 

SELECT ID_PATIENT,ALL_NAMES,AGE(CURRENT_DATE,BIRTHDAY) AS FULL_AGE, DATE_PART('year',AGE(CURRENT_DATE,BIRTHDAY)) AS YEAR_AGE
FROM CLINIC.PATIENT
WHERE SEX = 'F'
LIMIT 15;

-- DISPLAY ALL RECORDS THAT BEGINS WITH AN 'A' AND BIRTHDAY LESS THAN 2000

SELECT * -- NOT RECOMMENDED
FROM CLINIC.PATIENT
WHERE ALL_NAMES LIKE 'A%' AND DATE_PART('year',BIRTHDAY) < 2000
LIMIT 15;

-- DISPLAY PATIENTS WITH LVL_WEIGHT DIFFERENT FROM OBESIDAD AND THEIR HEIGHT MORE OR EQUALS TO 1.65 AND AGE LESS THAN 40

SELECT * -- NOT RECOMMENDED
FROM CLINIC.MED_RECORDS_DETAILS
WHERE LVL_WEIGHT <> 'SOBREPESO' AND HEIGHT_NBR >= '1.65' AND AGE_NBR < '40'
LIMIT 15;

/* SOME AGGREGATION FUNCTIONS */

-- DISPLAY COUNT PATIENTS BY STATE AND ORDERING DESCENDING

SELECT STATE_NM,COUNT(*) AS TOTAL_RECORDS-- NOT RECOMMENDED
FROM CLINIC.PATIENT
GROUP BY STATE_NM
ORDER BY STATE_NM DESC

-- GETTING THE AVERAGE AGE, THE MAXIMUM WIEGHT AND THE MINIMUM HEIGHT FROM PATIENTS GROUP BY 'OBESIDAD' OR 'SOBREPESO'

SELECT LVL_WEIGHT,AVG(CAST(AGE_NBR AS SMALLINT)) AS AVG_AGE, MAX(WEIGHT_NBR) AS MAX_WEIGHT, MIN(HEIGHT_NBR) AS MIN_HEIGHT -- NOT RECOMMENDED
FROM CLINIC.MED_RECORDS_DETAILS
WHERE LVL_WEIGHT IN ('SOBREPESO','OBESIDAD')
GROUP BY LVL_WEIGHT
LIMIT 55;


/* CREATE VIEWS */

-- CREATE VIEW HAS THE FULL NAME OF PATIENT, NUMBER PHONE,DATE AND HOUR FOR THE DATES BETWEEN 2022/10/01 AND 2022/10/03

CREATE OR REPLACE VIEW CLINIC.DATES_OCTOBER AS
SELECT CONCAT(A.ALL_NAMES,' ',A.LAST_NAME) AS FULL_NAME,A.PHONE_NBR,B.DATE_MED,B.DATE_HOUR
FROM CLINIC.PATIENT AS A
INNER JOIN CLINIC.DATE_MED AS B
ON (A.ID_PATIENT = B.ID_PATIENT)
WHERE B.DATE_MED BETWEEN '2022-10-01' AND '2022-10-03';


SELECT *
FROM CLINIC.DATES_OCTOBER

-- LETS ADD SOME NEW RECORDS


INSERT INTO CLINIC.PATIENT 
(
ID_PATIENT,
ALL_NAMES,
LAST_NAME,
SEX,
BIRTHDAY,
CITY,
STATE_NM,
PHONE_NBR
)
VALUES 
('P-0023', 'DANIEL', 'JUAREZ', 'M', '1998-03-10', 'MEXICO', 'MEXICO', '5579461308'),
('P-0026', 'ALEJANDRO', 'ZAVALA', 'M', '1998-03-10', 'MEXICO', 'MEXICO', '5531649782');


INSERT INTO CLINIC.DATE_MED
(
ID_DATE,
ID_PATIENT,
DATE_MED,
DATE_HOUR)
VALUES 
('CM-0011', 'P-0023', '2022-10-01', '08:30'),
('CM-0012', 'P-0026', '2022-10-01', '09:35');

-- CHECK. NOTICE THAT NEW RECORDS APPEARS, IT MEANS A VIEW DOES NOT STORAGE DATA
SELECT *
FROM CLINIC.DATES_OCTOBER

-- CHANGE NAME VIEW

ALTER VIEW CLINIC.DATES_OCTOBER RENAME TO DATES_OCTOBER_2022_1_TO_3;

SELECT *
FROM CLINIC.DATES_OCTOBER_2022_1_TO_3